[minone-rocky]
rocky-server ansible_host=172.16.25.61 ansible_user=eduardo ansible_ssh_private_key_file=../terraform/rocky/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_pass=123