# Inventario para la VM de openSUSE
[minone-suse]
suse-server ansible_host=127.0.0.1 ansible_user=vicente ansible_ssh_private_key_file=../terraform/opensuse/.ssh/id_ed25519 ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_ssh_pass=123